model_params:
  n_cropped_notes: 130
  z_dim: 32
  phrase_size: 256
  encoder_params:
    hidden_size: 512
    num_layers: 3
    n_tracks: 1
  decoder_params:
    hidden_size: 512
    num_layers: 3
    n_tracks: 1

data_params:
  tensor_folder: "../data/batches"
  batch_size: 16
  shuffle: True
  num_workers: 4
  batch_limit: 1

train_params:
  seed: 1
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
