model_params:
  in_channels: 3
  latent_dim: 128

data_params:
  tensor_folder: "../data/batches"
  batch_size: 16
  shuffle: True
  num_workers: 4

train_params:
  seed: 1
  gpus: 1
  max_nb_epochs: 50
  max_epochs: 30
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
