device: cuda

model_params:
  n_cropped_notes: 130
  z_dim: 32
  phrase_size: 256
  encoder_params:
    hidden_size: 32
    num_layers: 3
  decoder_params:
    hidden_size: 32
    num_layers: 3
    n_tracks: 1


data_params:
  tensor_folder: "../data/batches"
  batch_size: 16
  shuffle: True
  num_workers: 4
  batch_limit: 10000

train_params:
  seed: 1
  gpus: 1
  epochs: 2
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.999
  anneal_step: 1000
  clip_norm: 5
  beta: 0.1
  beta_increase: 0.0
  beta_increase_step: 1000
  beta_max: 100



output_params:
  save_dir: "../out/models"
  name: "MidiocrityVAE"
  print_step: 100
  save_step: 10000
