device: cuda

model_params:
  n_cropped_notes: 130
  z_dim: 2
  phrase_size: 256
  encoder_params:
    hidden_size: 16
    num_layers: 3
    n_tracks: 1
  decoder_params:
    hidden_size: 16
    num_layers: 3
    n_tracks: 1


data_params:
  tensor_folder: "../data/batches"
  batch_size: 16  # for even batches use factor of 1024
  shuffle: True
  num_workers: 0
  batch_limit: 2 # 10000

train_params:
  train_valid_test_split: [0.5, 0.5, 0.0] #[0.7, 0.2, 0.1]
  seed: 1
  gpus: 1
  epochs: 100000
  LR: 0.005
  weight_decay: 0.0 #0.0001
  scheduler_gamma: 0.999
  anneal_step: 1000
  clip_norm: 5
  beta_init: 0.000001
  beta_increase: 0.000001
  beta_increase_step_start: 1000
  beta_increase_step_rate : 1
  beta_max: 1.0



output_params:
  save_dir: "../out/"
  name: "MidiocrityVAE_2_sample"
  print_step: 1
  save_step: 100000000