device: cuda

model_params:
  n_cropped_notes: 130
  z_dim: 32
  phrase_size: 256
  encoder_params:
    hidden_size: 512
    num_layers: 3
    n_tracks: 1
  decoder_params:
    hidden_size: 512
    num_layers: 3
    n_tracks: 1


data_params:
  tensor_folder: "../data/batches"
  batch_size: 16  # pickled tensors are in 256 batches, for even batches use factor of 256
  shuffle: True
  num_workers: 4
  batch_limit: 10000

train_params:
  seed: 1
  gpus: 1
  epochs: 2
  LR: 0.005
  weight_decay: 0.0001
  scheduler_gamma: 0.999
  anneal_step: 1000
  clip_norm: 5
  beta_init: 0.0
  beta_increase: 0.2
  beta_increase_step_start: 1000
  beta_increase_step_rate : 100
  beta_max: 8



output_params:
  save_dir: "../out/models"
  name: "MidiocrityVAE"
  print_step: 10
  save_step: 10000
